# Site settings
title: SpeedTracker
description: Website performance monitoring tool
baseurl: ""
url: "https://speedtracker.org"

# Build settings
markdown: kramdown

toolkitUrl: "https://api.speedtracker.org"

detach:  false
port:    4830
host:    0.0.0.0

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/
